### ISSUE TITLE
Infinite exp from psychic lichen with modded exp boost

### ISSUE THREAD

**Issue by Rafasimon** [hjake123/reactive#12]
The psychic lichen can be used to generate infinite exp if combined with an exp boost mechanic from other mods.

When standing on a psychic lichen the players exp turned into exp orbs, but if there isn't room for the lichen to spread the orbs will be collected back by the player. If the player has any form of exp boost granted by other mods, the amount of exp collected will be greater than what was removed by the lichen, creating free exp.

I don't know if there is a way to fix this since this isn't a bug, but I thought you should know it anyways.

**Comment by hjake123** [comment]
Hm, interesting. I don't think xp boost is a Forge facility so I don't think there's an easy way to prevent this. 

I suppose I could add a (leas than 1) configurable multiplier for the XP dropped by the lichen but then the player would too quickly lose xp by standing on it. 

I could also add a config to just disable the ability of psychic lichen, but since it doesn't do anything else it'd be easier for modpack makers to make it uncraftable if there's the chance for an exploit.

**Comment by hjake123** [comment]
Come to think of it, which mod adds the xp boost you were using? Maybe I could add some kind of special case for just that mod

**Comment by hjake123** [comment]
Without further information, this issue can't be fixed. Pack makers, disable the recipe for the lichen if it causes this issue.

**Comment by hjake123** [comment]
Ah nevermind
